"""threads_count

Revision ID: b93382377ee1
Revises: ae6523b80620
Create Date: 2025-04-30 01:16:39.417497

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b93382377ee1"
down_revision: Union[str, None] = "ae6523b80620"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column(
            "threads_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
    )
    op.execute(
        """
    CREATE OR REPLACE FUNCTION update_post_thread_count() 
        RETURNS TRIGGER AS $$
        BEGIN
            UPDATE posts SET threads_count = threads_count + 1 WHERE id = NEW.post_id;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """
    )

    op.execute(
        """
    CREATE TRIGGER write_post_thread_count 
        AFTER INSERT ON threads
        FOR EACH ROW
        EXECUTE FUNCTION update_post_thread_count()
    """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "threads_count")
    op.execute("DROP TRIGGER IF EXISTS write_post_thread_count ON threads")
    op.execute("DROP FUNCTION IF EXISTS update_post_thread_count")
    # ### end Alembic commands ###
